/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CommandType {
    CommandType_CMD_UNKNOWN = 0,
    CommandType_CMD_SET_STATE = 1,
    CommandType_CMD_SET_CONFIG = 2,
    CommandType_CMD_HEARTBEAT = 3,
    CommandType_CMD_DISCOVERY_PING = 4,
    CommandType_CMD_DISCOVERY_PONG = 5
} CommandType;

typedef enum _DeviceState {
    DeviceState_STATE_OFF = 0,
    DeviceState_STATE_PREVIEW = 1,
    DeviceState_STATE_LIVE = 2
} DeviceState;

/* Struct definitions */
typedef struct _StatePayload {
    DeviceState state;
} StatePayload;

typedef struct _ConfigPayload {
    bool has_brightness;
    uint32_t brightness;
    bool has_wifi_ssid;
    char wifi_ssid[33];
    bool has_wifi_password;
    char wifi_password[64];
} ConfigPayload;

typedef struct _Payload {
    uint32_t magic_word;
    uint32_t version;
    CommandType command;
    pb_size_t which_data;
    union {
        StatePayload state_data;
        ConfigPayload config_data;
    } data;
} Payload;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CommandType_MIN CommandType_CMD_UNKNOWN
#define _CommandType_MAX CommandType_CMD_DISCOVERY_PONG
#define _CommandType_ARRAYSIZE ((CommandType)(CommandType_CMD_DISCOVERY_PONG+1))

#define _DeviceState_MIN DeviceState_STATE_OFF
#define _DeviceState_MAX DeviceState_STATE_LIVE
#define _DeviceState_ARRAYSIZE ((DeviceState)(DeviceState_STATE_LIVE+1))

#define StatePayload_state_ENUMTYPE DeviceState


#define Payload_command_ENUMTYPE CommandType


/* Initializer values for message structs */
#define StatePayload_init_default                {_DeviceState_MIN}
#define ConfigPayload_init_default               {false, 0, false, "", false, ""}
#define Payload_init_default                     {0, 0, _CommandType_MIN, 0, {StatePayload_init_default}}
#define StatePayload_init_zero                   {_DeviceState_MIN}
#define ConfigPayload_init_zero                  {false, 0, false, "", false, ""}
#define Payload_init_zero                        {0, 0, _CommandType_MIN, 0, {StatePayload_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define StatePayload_state_tag                   1
#define ConfigPayload_brightness_tag             1
#define ConfigPayload_wifi_ssid_tag              2
#define ConfigPayload_wifi_password_tag          3
#define Payload_magic_word_tag                   1
#define Payload_version_tag                      2
#define Payload_command_tag                      3
#define Payload_state_data_tag                   4
#define Payload_config_data_tag                  5

/* Struct field encoding specification for nanopb */
#define StatePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define StatePayload_CALLBACK NULL
#define StatePayload_DEFAULT NULL

#define ConfigPayload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   brightness,        1) \
X(a, STATIC,   OPTIONAL, STRING,   wifi_ssid,         2) \
X(a, STATIC,   OPTIONAL, STRING,   wifi_password,     3)
#define ConfigPayload_CALLBACK NULL
#define ConfigPayload_DEFAULT NULL

#define Payload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   magic_word,        1) \
X(a, STATIC,   SINGULAR, UINT32,   version,           2) \
X(a, STATIC,   SINGULAR, UENUM,    command,           3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,state_data,data.state_data),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,config_data,data.config_data),   5)
#define Payload_CALLBACK NULL
#define Payload_DEFAULT NULL
#define Payload_data_state_data_MSGTYPE StatePayload
#define Payload_data_config_data_MSGTYPE ConfigPayload

extern const pb_msgdesc_t StatePayload_msg;
extern const pb_msgdesc_t ConfigPayload_msg;
extern const pb_msgdesc_t Payload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StatePayload_fields &StatePayload_msg
#define ConfigPayload_fields &ConfigPayload_msg
#define Payload_fields &Payload_msg

/* Maximum encoded size of messages (where known) */
#define ConfigPayload_size                       105
#define PROTOCOL_PB_H_MAX_SIZE                   Payload_size
#define Payload_size                             121
#define StatePayload_size                        2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
