# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"+\n\x0cStatePayload\x12\x1b\n\x05state\x18\x01 \x01(\x0e\x32\x0c.DeviceState\"\x8b\x01\n\rConfigPayload\x12\x17\n\nbrightness\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\twifi_ssid\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rwifi_password\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_brightnessB\x0c\n\n_wifi_ssidB\x10\n\x0e_wifi_password\"\xa1\x01\n\x07Payload\x12\x12\n\nmagic_word\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x1d\n\x07\x63ommand\x18\x03 \x01(\x0e\x32\x0c.CommandType\x12#\n\nstate_data\x18\x04 \x01(\x0b\x32\r.StatePayloadH\x00\x12%\n\x0b\x63onfig_data\x18\x05 \x01(\x0b\x32\x0e.ConfigPayloadH\x00\x42\x06\n\x04\x64\x61ta*\x88\x01\n\x0b\x43ommandType\x12\x0f\n\x0b\x43MD_UNKNOWN\x10\x00\x12\x11\n\rCMD_SET_STATE\x10\x01\x12\x12\n\x0e\x43MD_SET_CONFIG\x10\x02\x12\x11\n\rCMD_HEARTBEAT\x10\x03\x12\x16\n\x12\x43MD_DISCOVERY_PING\x10\x04\x12\x16\n\x12\x43MD_DISCOVERY_PONG\x10\x05*?\n\x0b\x44\x65viceState\x12\r\n\tSTATE_OFF\x10\x00\x12\x11\n\rSTATE_PREVIEW\x10\x01\x12\x0e\n\nSTATE_LIVE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=370
  _globals['_COMMANDTYPE']._serialized_end=506
  _globals['_DEVICESTATE']._serialized_start=508
  _globals['_DEVICESTATE']._serialized_end=571
  _globals['_STATEPAYLOAD']._serialized_start=18
  _globals['_STATEPAYLOAD']._serialized_end=61
  _globals['_CONFIGPAYLOAD']._serialized_start=64
  _globals['_CONFIGPAYLOAD']._serialized_end=203
  _globals['_PAYLOAD']._serialized_start=206
  _globals['_PAYLOAD']._serialized_end=367
# @@protoc_insertion_point(module_scope)
