/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(StatePayload, StatePayload, AUTO)


PB_BIND(ConfigPayload, ConfigPayload, AUTO)


PB_BIND(Payload, Payload, AUTO)







