/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTOCOL_V1_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOCOL_V1_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _protocol_v1_State {
    protocol_v1_State_STATE_UNSPECIFIED = 0,
    protocol_v1_State_STATE_BOOT = 1,
    protocol_v1_State_STATE_STANDBY = 2,
    protocol_v1_State_STATE_PREVIEW = 3,
    protocol_v1_State_STATE_LIVE = 4,
    protocol_v1_State_STATE_CONFIG = 5,
    protocol_v1_State_STATE_SHUTDOWN = 6,
    protocol_v1_State_STATE_ERROR = 7
} protocol_v1_State;

typedef enum _protocol_v1_PowerMode {
    protocol_v1_PowerMode_POWER_MODE_UNSPECIFIED = 0,
    protocol_v1_PowerMode_POWER_MODE_NORMAL = 1,
    protocol_v1_PowerMode_POWER_MODE_ECO = 2,
    protocol_v1_PowerMode_POWER_MODE_SLEEP = 3
} protocol_v1_PowerMode;

typedef enum _protocol_v1_ChargeState {
    protocol_v1_ChargeState_CHARGE_STATE_UNSPECIFIED = 0,
    protocol_v1_ChargeState_CHARGE_STATE_DISCHARGING = 1,
    protocol_v1_ChargeState_CHARGE_STATE_CHARGING = 2,
    protocol_v1_ChargeState_CHARGE_STATE_FULL = 3
} protocol_v1_ChargeState;

/* Struct definitions */
typedef struct _protocol_v1_NetworkConfig {
    bool has_ssid;
    char ssid[33];
    bool has_password;
    char password[65]; /* Hier könnten später static_ip, gateway, subnet_mask hinzukommen */
} protocol_v1_NetworkConfig;

typedef struct _protocol_v1_DeviceConfig {
    bool has_device_name;
    char device_name[32]; /* z.B. "Cam 1" */
    bool has_master_brightness;
    int32_t master_brightness; /* 0-100% */
    bool has_power_mode;
    protocol_v1_PowerMode power_mode;
} protocol_v1_DeviceConfig;

typedef struct _protocol_v1_Telemetry {
    int32_t battery_percentage;
    protocol_v1_ChargeState charge_state;
    int32_t rssi;
    float temperature_c;
    uint32_t uptime_seconds;
    float battery_voltage;
} protocol_v1_Telemetry;

typedef struct _protocol_v1_HubToTally {
    uint32_t message_id;
    bool has_set_state;
    protocol_v1_State set_state;
    bool has_set_network;
    protocol_v1_NetworkConfig set_network;
    bool has_set_device;
    protocol_v1_DeviceConfig set_device;
    bool has_trigger_identify;
    bool trigger_identify; /* Tally blinkt kurz */
    bool has_trigger_reboot;
    bool trigger_reboot; /* Tally startet neu */
} protocol_v1_HubToTally;

typedef struct _protocol_v1_TallyToHub {
    protocol_v1_State current_state;
    bool has_telemetry;
    protocol_v1_Telemetry telemetry;
    bool has_ack_message_id;
    uint32_t ack_message_id;
    bool has_error_message;
    char error_message[64];
} protocol_v1_TallyToHub;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _protocol_v1_State_MIN protocol_v1_State_STATE_UNSPECIFIED
#define _protocol_v1_State_MAX protocol_v1_State_STATE_ERROR
#define _protocol_v1_State_ARRAYSIZE ((protocol_v1_State)(protocol_v1_State_STATE_ERROR+1))

#define _protocol_v1_PowerMode_MIN protocol_v1_PowerMode_POWER_MODE_UNSPECIFIED
#define _protocol_v1_PowerMode_MAX protocol_v1_PowerMode_POWER_MODE_SLEEP
#define _protocol_v1_PowerMode_ARRAYSIZE ((protocol_v1_PowerMode)(protocol_v1_PowerMode_POWER_MODE_SLEEP+1))

#define _protocol_v1_ChargeState_MIN protocol_v1_ChargeState_CHARGE_STATE_UNSPECIFIED
#define _protocol_v1_ChargeState_MAX protocol_v1_ChargeState_CHARGE_STATE_FULL
#define _protocol_v1_ChargeState_ARRAYSIZE ((protocol_v1_ChargeState)(protocol_v1_ChargeState_CHARGE_STATE_FULL+1))


#define protocol_v1_DeviceConfig_power_mode_ENUMTYPE protocol_v1_PowerMode

#define protocol_v1_Telemetry_charge_state_ENUMTYPE protocol_v1_ChargeState

#define protocol_v1_HubToTally_set_state_ENUMTYPE protocol_v1_State

#define protocol_v1_TallyToHub_current_state_ENUMTYPE protocol_v1_State


/* Initializer values for message structs */
#define protocol_v1_NetworkConfig_init_default   {false, "", false, ""}
#define protocol_v1_DeviceConfig_init_default    {false, "", false, 0, false, _protocol_v1_PowerMode_MIN}
#define protocol_v1_Telemetry_init_default       {0, _protocol_v1_ChargeState_MIN, 0, 0, 0, 0}
#define protocol_v1_HubToTally_init_default      {0, false, _protocol_v1_State_MIN, false, protocol_v1_NetworkConfig_init_default, false, protocol_v1_DeviceConfig_init_default, false, 0, false, 0}
#define protocol_v1_TallyToHub_init_default      {_protocol_v1_State_MIN, false, protocol_v1_Telemetry_init_default, false, 0, false, ""}
#define protocol_v1_NetworkConfig_init_zero      {false, "", false, ""}
#define protocol_v1_DeviceConfig_init_zero       {false, "", false, 0, false, _protocol_v1_PowerMode_MIN}
#define protocol_v1_Telemetry_init_zero          {0, _protocol_v1_ChargeState_MIN, 0, 0, 0, 0}
#define protocol_v1_HubToTally_init_zero         {0, false, _protocol_v1_State_MIN, false, protocol_v1_NetworkConfig_init_zero, false, protocol_v1_DeviceConfig_init_zero, false, 0, false, 0}
#define protocol_v1_TallyToHub_init_zero         {_protocol_v1_State_MIN, false, protocol_v1_Telemetry_init_zero, false, 0, false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define protocol_v1_NetworkConfig_ssid_tag       1
#define protocol_v1_NetworkConfig_password_tag   2
#define protocol_v1_DeviceConfig_device_name_tag 1
#define protocol_v1_DeviceConfig_master_brightness_tag 2
#define protocol_v1_DeviceConfig_power_mode_tag  3
#define protocol_v1_Telemetry_battery_percentage_tag 1
#define protocol_v1_Telemetry_charge_state_tag   2
#define protocol_v1_Telemetry_rssi_tag           3
#define protocol_v1_Telemetry_temperature_c_tag  4
#define protocol_v1_Telemetry_uptime_seconds_tag 5
#define protocol_v1_Telemetry_battery_voltage_tag 6
#define protocol_v1_HubToTally_message_id_tag    1
#define protocol_v1_HubToTally_set_state_tag     2
#define protocol_v1_HubToTally_set_network_tag   3
#define protocol_v1_HubToTally_set_device_tag    4
#define protocol_v1_HubToTally_trigger_identify_tag 5
#define protocol_v1_HubToTally_trigger_reboot_tag 6
#define protocol_v1_TallyToHub_current_state_tag 1
#define protocol_v1_TallyToHub_telemetry_tag     2
#define protocol_v1_TallyToHub_ack_message_id_tag 3
#define protocol_v1_TallyToHub_error_message_tag 4

/* Struct field encoding specification for nanopb */
#define protocol_v1_NetworkConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   ssid,              1) \
X(a, STATIC,   OPTIONAL, STRING,   password,          2)
#define protocol_v1_NetworkConfig_CALLBACK NULL
#define protocol_v1_NetworkConfig_DEFAULT NULL

#define protocol_v1_DeviceConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   device_name,       1) \
X(a, STATIC,   OPTIONAL, INT32,    master_brightness,   2) \
X(a, STATIC,   OPTIONAL, UENUM,    power_mode,        3)
#define protocol_v1_DeviceConfig_CALLBACK NULL
#define protocol_v1_DeviceConfig_DEFAULT NULL

#define protocol_v1_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    battery_percentage,   1) \
X(a, STATIC,   SINGULAR, UENUM,    charge_state,      2) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_c,     4) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    5) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,   6)
#define protocol_v1_Telemetry_CALLBACK NULL
#define protocol_v1_Telemetry_DEFAULT NULL

#define protocol_v1_HubToTally_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        1) \
X(a, STATIC,   OPTIONAL, UENUM,    set_state,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  set_network,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  set_device,        4) \
X(a, STATIC,   OPTIONAL, BOOL,     trigger_identify,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     trigger_reboot,    6)
#define protocol_v1_HubToTally_CALLBACK NULL
#define protocol_v1_HubToTally_DEFAULT NULL
#define protocol_v1_HubToTally_set_network_MSGTYPE protocol_v1_NetworkConfig
#define protocol_v1_HubToTally_set_device_MSGTYPE protocol_v1_DeviceConfig

#define protocol_v1_TallyToHub_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    current_state,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  telemetry,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   ack_message_id,    3) \
X(a, STATIC,   OPTIONAL, STRING,   error_message,     4)
#define protocol_v1_TallyToHub_CALLBACK NULL
#define protocol_v1_TallyToHub_DEFAULT NULL
#define protocol_v1_TallyToHub_telemetry_MSGTYPE protocol_v1_Telemetry

extern const pb_msgdesc_t protocol_v1_NetworkConfig_msg;
extern const pb_msgdesc_t protocol_v1_DeviceConfig_msg;
extern const pb_msgdesc_t protocol_v1_Telemetry_msg;
extern const pb_msgdesc_t protocol_v1_HubToTally_msg;
extern const pb_msgdesc_t protocol_v1_TallyToHub_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protocol_v1_NetworkConfig_fields &protocol_v1_NetworkConfig_msg
#define protocol_v1_DeviceConfig_fields &protocol_v1_DeviceConfig_msg
#define protocol_v1_Telemetry_fields &protocol_v1_Telemetry_msg
#define protocol_v1_HubToTally_fields &protocol_v1_HubToTally_msg
#define protocol_v1_TallyToHub_fields &protocol_v1_TallyToHub_msg

/* Maximum encoded size of messages (where known) */
#define PROTOCOL_V1_PROTOCOL_PB_H_MAX_SIZE       protocol_v1_HubToTally_size
#define protocol_v1_DeviceConfig_size            46
#define protocol_v1_HubToTally_size              162
#define protocol_v1_NetworkConfig_size           100
#define protocol_v1_TallyToHub_size              115
#define protocol_v1_Telemetry_size               40

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
