/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_v1_NetworkConfig, protocol_v1_NetworkConfig, AUTO)


PB_BIND(protocol_v1_DeviceConfig, protocol_v1_DeviceConfig, AUTO)


PB_BIND(protocol_v1_Telemetry, protocol_v1_Telemetry, AUTO)


PB_BIND(protocol_v1_HubToTally, protocol_v1_HubToTally, AUTO)


PB_BIND(protocol_v1_TallyToHub, protocol_v1_TallyToHub, AUTO)









